### ISSUE TITLE
YAML vs. JSON for Metadata

### ISSUE THREAD

**Issue by scovetta** [ossf/security-reviews#17]
We should decide on the format for the metadata. Options are YAML or JSON. Here are what they would look like:

### YAML
```
---
Publication-State: active
Reviewers:
- Name: Michael Scovetta
  Email: michael.scovetta@microsoft.com
  Organization: Microsoft
  Associated-With-Project: true
  Compensation-Source: None
Domain: Security
Methodology:
- Static-Analysis
- Code-Review
- Web-Search
Issues-Identified:
- None
Package-URLs:
- pkg:npm/left-pad@1.2.0
- pkg:npm/left-pad@1.3.0
Date-Reviewed: '2021-02-01'
Scope: Implementation/Full
Schema-Version: '1.0'
SPDX-License-Identifier: CC-BY-4.0

```

### JSON
```
{
	"Publication-State": "active",
	"Reviewers": [
		{
			"Name": "Michael Scovetta",
			"Email": "michael.scovetta@microsoft.com",
			"Organization": "Microsoft",
			"Associated-With-Project": true,
			"Compensation-Source": "None"
		}
	],
	"Domain": "Security",
	"Methodology": [
		"Static-Analysis",
		"Code-Review",
		"Web-Search"
	],
	"Issues-Identified": [
		"None"
	],
	"Package-URLs": [
            "pkg:npm/left-pad@1.2.0",
            "pkg:npm/left-pad@1.3.0"
	],
	"Date-Reviewed": "2021-02-01",
	"Scope": "Implementation/Full",
	"Schema-Version": "1.0",
	"SPDX-License-Identifier": "CC-BY-4.0"
}
```

Since these both convey the same information, I don't know how important this decision is, but if anyone has strong opinions, please comment on this thread and we'll go with the majority opinion. 

Differences:

* YAML has fewer lines, brackets, etc.
* JSON can have a formal schema (not sure if YAML does)
* [Comparison of YAML vs JSON](https://en.wikipedia.org/wiki/YAML#Comparison_with_JSON)
